name: Fetch Repository Issues

on:
  workflow_dispatch:

jobs:
  fetch-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Retrieve Issues
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 100
              }
            );

            for (const issue of issues) {
              console.log(`#${issue.number}: ${issue.title} → ${issue.html_url}`);
            }